site:
  since: 2015
  rss:
    enabled: true

menu:
  - name: 首页
    url: /
  - name: 归档
    url: /archives
  - name: 分类
    url: /categories
  - name: 标签
    url: /tags

comments:
  enabled: true
  provider: disqus
  disqus:
    shortname: "acris"

analytics:
  google:
    enabled: true
    id: "G-SSN1WL65KY"
