site:
  since: 2015
  rss:
    enabled: true

menu:
  - name: 首页
    url: /
  - name: 归档
    url: /archives
  - name: 分类
    url: /categories
  - name: 标签
    url: /tags

comments:
  enabled: true
  provider: giscus
  giscus:
    repo: "Acris/blog"
    repo_id: "MDEwOlJlcG9zaXRvcnk4ODMyNDg0Mg=="
    category: "Giscus"
    category_id: "DIC_kwDOBUO66s4C4WNz"
    strict: 1
    input_position: top
    lang: zh-CN

analytics:
  google:
    enabled: true
    id: "G-SSN1WL65KY"
